### ISSUE TITLE
Napari failing to install (Macbook M1)

### ISSUE THREAD

**Issue by conditg** [agencyenterprise/neurotechdevkit#119]
## Describe the bug

This is likely an upstream issue, but I'm documenting it here for discussion and visibility. I can't get the 3D visualizations working because the `napari` package won't install on mac locally. 

## Steps to reproduce

* setup the environment using poetry
* env
    *  Python 3.9.16
    * pip 23.1.2
    * conda 23.1.0
    * Poetry (version 1.4.2)
`{
'system': 'Darwin', 
'node': 'Gregs-MBP', 
'release': '22.5.0', 
'version': 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000', 'machine': 'arm64'
}`

Then, run `pip install "napari[all]"`

## Expected results

napari installs successfully

## Actual results

    
```

Collecting PyQt5!=5.15.0,>=5.12.3 (from napari[all])
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/9j/vq3r860d6g528nr3x98p0gdh0000gn/T/pip-build-env-lq1j9ann/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/9j/vq3r860d6g528nr3x98p0gdh0000gn/T/pip-build-env-lq1j9ann/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/9j/vq3r860d6g528nr3x98p0gdh0000gn/T/pip-build-env-lq1j9ann/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 602, in setup
          self.update(tool)
        File "project.py", line 165, in update
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

# Other things I tried:

### Install with Conda

`conda install -c conda-forge napari`

Outcome: 
This 'succeeded' with a warning
```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::typing-extensions==4.5.0=hd8ed1ab_0
  - conda-forge/noarch::prompt_toolkit==3.0.38=hd8ed1ab_0

```

but now, I can't import the NDK at all:

```
Python 3.9.16 (main, Mar  8 2023, 04:29:24) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari
>>> import neurotechdevkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gregcondit/dsprojects/bci/neurotechdevkit/src/neurotechdevkit/__init__.py", line 6, in <module>
    from . import scenarios, sources
  File "/Users/gregcondit/dsprojects/bci/neurotechdevkit/src/neurotechdevkit/scenarios/__init__.py", line 3, in <module>
    from ._base import Scenario, Scenario2D, Scenario3D, Target
  File "/Users/gregcondit/dsprojects/bci/neurotechdevkit/src/neurotechdevkit/scenarios/_base.py", line 13, in <module>
    import stride
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/stride/__init__.py", line 47, in <module>
    from .problem import *
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/stride/problem/__init__.py", line 3, in <module>
    from .acquisitions import *
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/stride/problem/acquisitions.py", line 19, in <module>
    from .data import Traces
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/stride/problem/data.py", line 5, in <module>
    import scipy.ndimage
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/ndimage/__init__.py", line 154, in <module>
    from ._interpolation import *  # noqa: F401 F403
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/ndimage/_interpolation.py", line 37, in <module>
    from scipy import special
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/special/__init__.py", line 780, in <module>
    from . import _orthogonal
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/special/_orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 225, in <module>
    from ._sketches import *
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/linalg/_sketches.py", line 9, in <module>
    from scipy.sparse import csc_matrix
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 287, in <module>
    from . import csgraph
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/csgraph/__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/__init__.py", line 130, in <module>
    from . import isolve, dsolve, interface, eigen, matfuncs
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/isolve/__init__.py", line 4, in <module>
    from .iterative import *
  File "/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/isolve/iterative.py", line 8, in <module>
    from . import _iterative
ImportError: dlopen(/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib
  Referenced from: <7C5CA485-4827-31D0-A732-8493637A00FE> /Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-39-darwin.so
  Reason: tried: '/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/isolve/../../../../../../liblapack.3.dylib' (no such file), '/Users/gregcondit/miniconda3/envs/ndk/lib/python3.9/site-packages/scipy/sparse/linalg/isolve/../../../../../../liblapack.3.dylib' (no such file), '/Users/gregcondit/miniconda3/envs/ndk/bin/../lib/liblapack.3.dylib' (no such file), '/Users/gregcondit/miniconda3/envs/ndk/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)
```

**Comment by charlesincharge** [comment]
Qt5 is not supported on macOS M1, only Qt6. Seems like `napari[all]` specifies `pyqt5`, which is why this fails: https://github.com/napari/napari/blob/main/setup.cfg#L111. @NewtonSander, maybe the recommendation should be `napari[pyside6_experimental]` for Mac M1 users?

**Comment by charlesincharge** [comment]
I ran into this on another package (NDS) and knew how to fix it already, so I just opened a PR to update the documentation.
